services:
  db:
    image: mysql:8.0
    container_name: learning-sql-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: sakila
    volumes:
      # Persist MySQL data in this repo
      - ./.data:/var/lib/mysql

      # Run schema before data (order matters)
      - ./init/sakila-schema.sql:/docker-entrypoint-initdb.d/01-sakila-schema.sql:ro
      - ./init/sakila-data.sql:/docker-entrypoint-initdb.d/02-sakila-data.sql:ro
